apiVersion: v1
kind: Pod
metadata:
  name: temp-pod
  namespace: observability
spec:
  containers:
    - name: temp-container
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - name: log-server
          mountPath: /mnt
  volumes:
    - name: log-server
      persistentVolumeClaim:
        claimName: log-server-pvc
