apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-fluentd
  labels:
    app: fluentd
spec:
  replicas: {{ .Values.replicas | default 1 }}
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      containers:
        - name: fluentd
          image: "{{ .Values.fluentd.image.repository }}:{{ .Values.fluentd.image.tag }}"
          imagePullPolicy: {{ .Values.fluentd.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.fluentd.service.port }}
          volumeMounts:
            {{- range .Values.fluentd.volumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
      volumes:
        {{- range .Values.fluentd.volumes }}
        - name: {{ .name }}
          {{- if .configMap }}
          configMap:
            name: {{ .configMap.name }}
          {{- end }}
          {{- if .persistentVolumeClaim }}
          persistentVolumeClaim:
            claimName: {{ .persistentVolumeClaim.claimName }}
          {{- end }}
        {{- end }}
