apiVersion: v2
name: efk-stack
description: A Helm chart for deploying the EFK stack (Elasticsearch, Fluentd, Kibana)
type: application
version: 0.1.0
appVersion: "7.17.0" # Example version for Elasticsearch and Kibana
