elasticsearch:
  image:
    repository: docker.elastic.co/elasticsearch/elasticsearch
    tag: 7.13.1
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 9200
  environment:
    - name: discovery.type
      value: single-node
    - name: xpack.security.enabled
      value: "false" # Disable security for testing
    - name: ES_JAVA_OPTS
      value: "-Xms2g -Xmx2g" # Set heap size to 2GB
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
    interval: 10s
    retries: 5
    timeout: 5s
  resources:
    requests:
      memory: "4Gi" # Reduce memory request
      cpu: "1" # Reduce CPU request
    limits:
      memory: "4Gi" # Reduce memory limit
      cpu: "2" # Reduce CPU limit

kibana:
  image:
    repository: docker.elastic.co/kibana/kibana
    tag: 7.13.1
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 5601

fluentd:
  image:
    repository: namcnab/fluentd-elasticsearch
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    ports:
      - name: tcp
        containerPort: 24224
        protocol: TCP
      - name: udp
        containerPort: 24224
        protocol: UDP
  volumes:
    - name: log-server
      mountPath: /app/logs
    - name: fluentd-config
      mountPath: /fluentd/etc
      subPath: fluent.conf

serviceAccount:
  create: true

service:
  annotations: {}

ingress:
  enabled: false

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 75

resources:
  requests:
    memory: "10Gi" # Minimum memory Elasticsearch can use
    cpu: "2"
  limits:
    memory: "16Gi" # Maximum memory Elasticsearch can use
    cpu: "4"
