services:
  coding-challenge-service:
    image: calculator-api
    container_name: calculator
    volumes:
      - log-server:/app/logs
    networks:
      - efk-network
    ports:
      - "3333:3333"

volumes:
  log-server: 
    name: log-server

networks:
  efk-network:
    driver: bridge