services:
  coding-challenge-service:
    image: calculator-api
    container_name: calculator
    volumes:
      - log-server:/app/logs
    networks:
      - efk-network
    ports:
      - "8080:8080"

volumes:
  log-server:
    external: true

networks:
  efk-network:
    driver: bridge