apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: log-server
  name: log-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
