services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080" # Expose Jenkins on localhost:8080
      - "50000:50000" # Port for Jenkins agents
    volumes:
      - jenkins_home:/var/jenkins_home # Persist Jenkins data
    restart: unless-stopped

volumes:
  jenkins_home: