apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "efk-stack.fullname" . }}
  labels:
    {{- include "efk-stack.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount | default 1 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "efk-stack.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "efk-stack.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "efk-stack.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        {{- range $serviceName, $service := .Values }}
        {{- if $service.image }}
        - name: "{{ $serviceName }}"
          image: "{{ $service.image.repository }}:{{ $service.image.tag | default "latest" }}"
          imagePullPolicy: {{ $service.image.pullPolicy | default "IfNotPresent" }}
          ports:
            {{- if $service.service.port }}
            - containerPort: {{ $service.service.port }}
              protocol: TCP
            {{- else if $service.service.ports }}
            {{- range $port := $service.service.ports }}
            - containerPort: {{ $port.containerPort }}
              protocol: {{ $port.protocol }}
            {{- end }}
            {{- end }}
          {{- if $service.environment }}
          env:
            {{- toYaml $service.environment | nindent 12 }}
          {{- end }}
          {{- with $service.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $service.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $service.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $service.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
        {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}