apiVersion: v1
kind: Service
metadata:
  name: {{ include "efk-stack.fullname" . }}
  labels:
    {{- include "efk-stack.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default "http" }}
      protocol: TCP
      name: {{ .Values.service.name | default "http" }}
  selector:
    {{- include "efk-stack.selectorLabels" . | nindent 4 }}
