{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "efk-stack.serviceAccountName" . }}
  labels:
    {{- include "efk-stack.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- if .Values.serviceAccount.automountServiceAccountToken | default true }}
automountServiceAccountToken: true
{{- end }}
{{- end }}
