apiVersion: v1
kind: Service
metadata:
  name: calculator-api-service
  namespace: calculator-namespace
spec:
  selector:
    app: calculator-api
  ports:
    - protocol: TCP
      port: 3001 # External port
      targetPort: 3333 # Port exposed by the container
  type: LoadBalancer # Use LoadBalancer for external access
