# filepath: /Users/nausicaa/Documents/Repos/calculator/configs/kubernetes/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-namespace-reader-binding
subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: calculator-namespace
roleRef:
  kind: ClusterRole
  name: jenkins-namespace-reader
  apiGroup: rbac.authorization.k8s.io
