apiVersion: v1
kind: Secret
metadata:
  name: jenkins-token
  namespace: calculator-namespace # Ensure this matches the namespace of the service account
  annotations:
    kubernetes.io/service-account.name: jenkins
type: kubernetes.io/service-account-token
